version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12.16.2

orbs:
  aws-cli: circleci/aws-cli@1.2.0
  serverless: circleci/serverless-framework@1.0.1

commands:
  save_app_modules:
    steps:
      - save_cache:
          paths: ~/workspace/node_modules
          key: modules-{{ .Branch }}-{{ checksum "package-lock.json" }}

  restore_app_modules:
    steps:
      - restore_cache:
          key: modules-{{ .Branch }}-{{ checksum "package-lock.json" }}

jobs:
  install:
    executor: default
    steps:
      - checkout
      - restore_app_modules
      - run:
          name: install
          command: npm install
      - save_app_modules
  deploy:
    executor: default
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
      - checkout
      - restore_app_modules
      - aws-cli/setup
      - serverless/setup
      - run:
          name: build
          command: npm run build
      - run:
          name: deploy
          command: npm run deploy

workflows:
  process:
    jobs:
      - install
      - deploy:
          requires:
            - install
          filters:
            branches:
              only: master
